### ISSUE TITLE
Permission denied when i try grant role_admin in RDS

### ISSUE THREAD

**Issue by SamuelMolling** [petoju/terraform-provider-mysql#110]
I'm creating a migration role and creating a user called usr_migration. When I try to grant migration permission to usr_migration in Amazon RDS, I get a permission denied error. I did some research and discovered that it is necessary to grant the ROLE_ADMIN grant to the admin user. When I do it manually, this works well and I can then give migration permission to usr_migration. The problem is that when I try to give a grant to the admin user of role_admin using mysql_grant, it gives me errors that the user has permissions, but they are not being managed by Terraform. Which makes sense, but I don't know how to solve the problem.

I need a grant on the admin user, before granting permission to another user.

Here's what I tested.

```
# ------------------------------------------------------------------------------
# MYSQL ROLE_ADMIN
# ------------------------------------------------------------------------------
resource "mysql_grant" "default" {
  user       = "root"
  database   = "*"
  privileges = ["ROLE_ADMIN"]
  host       = "%"
}
```

```
╷
│ Error: user/role {root %} already has unmanaged grant &{* * [ALTER ALTER ROUTINE CREATE CREATE ROUTINE CREATE TEMPORARY TABLES CREATE USER CREATE VIEW DELETE DROP EVENT EXECUTE INDEX INSERT LOCK TABLES PROCESS REFERENCES RELOAD REPLICATION CLIENT REPLICATION SLAVE SELECT SHOW DATABASES SHOW VIEW TRIGGER UPDATE] true {root %} NONE} - import it first
│ 
│   with module.mysql_roles.mysql_grant.default,
│   on .terraform/modules/mysql_roles/db_initial_config_mysql/main.tf line 11, in resource "mysql_grant" "default":
│   11: resource "mysql_grant" "default" {
│ 
╵
```

Has anyone ever experienced this?

**Comment by SamuelMolling** [comment]
@petoju Can you tell?

**Comment by SamuelMolling** [comment]
Importing is not an option. The developer who creates the resource is the one who doesn't know terraform or infrastructure. He just wants his database with the user.

Is it not possible to create a resource to execute a query so I would grant the grant via SQL? Or a resource that only manages privileges that were granted by terraform?

The problem is that RDS does not give the necessary permissions by default to the root user (role_admin, admin or super). He has certain privileges that come by default, but I just wanted to grant one role.

**Comment by SamuelMolling** [comment]
I managed to solve it using the [sql provider](https://registry.terraform.io/providers/paultyng/sql/latest/docs) and running grant in sql.

**Comment by petoju** [comment]
> Importing is not an option. The developer who creates the resource is the one who doesn't know terraform or infrastructure. He just wants his database with the user.

FYI if you created some new user (I mean really new, not with existing permissions), there wouldn't be any issues like this. And revoke/extension would work as expected with terraform.

Importing is not that difficult - with new import block, one has to find out only import string and call "apply".

**Comment by SamuelMolling** [comment]
I cannot create a user granting the role I need, if my user does not have the role in RDS. Maybe with import and then granting it, it would work too.
