### ISSUE TITLE
GCP Cloud SQL - Add support for PRIVATE_IP 

### ISSUE THREAD

**Issue by 6uellerBpanda** [petoju/terraform-provider-mysql#117]
Hi

We're using for our Cloud SQL instances private ip option. The `cloud.google.com/go/cloudsqlconn` has the necessary https://pkg.go.dev/cloud.google.com/go/cloudsqlconn#WithPrivateIP option but it's missing at the [provider](https://github.com/petoju/terraform-provider-mysql/blob/0c455c401a07c43b82c086d2ae69b2817cc3af11/mysql/provider.go#L261).

It would be great if this would be possible to set. thanks.

The terraform run fails when specifying `endpoint = "cloudsql://<INSTANCE>"`:

### Debug Output
`│ Error: failed getting database from Meta: failed to connect to MySQL: could not create new connection: could not connect to server: Config error: instance does not have IP of type "PUBLIC" (connection name = "<INSTANCE>")`

### References
- GH-40

**Comment by petoju** [comment]
Two fixes come to my mind:
1. Add it to endpoint and strip it when connecting
2. Add another field called like `endpointParams`

Both are fine, but I cannot easily test it now. PRs are welcome.

**Comment by petoju** [comment]
This was released
