### ISSUE TITLE
Support `SET DEFAULT ROLE` Statement 

### ISSUE THREAD

**Issue by alanwu4321** [petoju/terraform-provider-mysql#119]
Do we have support for [`SET DEFAULT ROLE`](https://dev.mysql.com/doc/refman/8.0/en/set-default-role.html
) on user? 

```sql
SET DEFAULT ROLE
    {NONE | ALL | role [, role ] ...}
    TO user [, user ] ...
```

If not I can help contribute :) Would like some pointers

Maybe something like this? @petoju 
```tf
...

resource "mysql_default_role" "developer" {
  user     = mysql_user.jdoe.user
  host     = mysql_user.jdoe.host
  role    = mysql_role.developer.name
}
```

**Comment by petoju** [comment]
The new resource was released as a part of provider version 3.0.55 - thanks to @rneascu5
