### ISSUE TITLE
Request to Publish Latest Version on Terraform Registry

### ISSUE THREAD

**Issue by kenchan0130** [petoju/terraform-provider-mysql#127]
Hello @petoju,

I kindly request that the latest version (v3.0.51) of the Terraform provider be published on the Terraform Registry. As users, we greatly appreciate having access to the most up-to-date features and improvements.

Thank you for your attention to this matter!

Best regards,
kenchan0130

**Comment by brianpham** [comment]
We are waiting for the latest version as well since there are some fixes we are hoping to get in v3.0.51.

**Comment by petoju** [comment]
Terraform registry should automatically pull the release.

It did not happen this time for an unknown reason - I manually clicked on "Sync with Github" and the release is visible there.
