### ISSUE TITLE
Resource for tidb dynamic config

### ISSUE THREAD

**Issue by borissavelev** [petoju/terraform-provider-mysql#15]
It's not an issue but I'd like to have a consultation before writing code)
There is a TiDB which is 99% compatible with MySQL.
TiDB has extension to manage configuration dynamicaly https://docs.pingcap.com/tidb/stable/dynamic-config the same way as global variables (with SQL)

What do you think about having another resource type `mysql_tidb_config` with semantic

```hcl
type = "ENUM('pd', 'tikv')"
name = "string"
value = "string"
```

and example usage like:
```hcl
resource "mysql_tidb_config" "this" {
  type = "pd"
  name = "log.level"
  value = "info"
}
```

**Comment by petoju** [comment]
It doesn't add any dependency and it looks good enough.

For discoverability, it would be better if TiDB had its own provider - that said, I'm fine with merging the change you're suggesting as long as it fulfills quality standards (tests, docs).
