### ISSUE TITLE
User password created with deprecated plugin

### ISSUE THREAD

**Issue by charles-ballario-wmx** [petoju/terraform-provider-mysql#168]
Hi,

I see that to create user passwords the `mysql_native_password` plugin is used.

However, with MySQL 8.x I receive the warning:

```
Plugin mysql_native_password reported: ''mysql_native_password'
is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
```

Do you plan to fix that and use the `caching_sha2_password` plugin instead ?

**Comment by petoju** [comment]
Hi @charles-ballario-wmx 

I believe this plugin uses the default on the server - isn't it? I don't think we specify anything explicitly.

What's your server setting?
