### ISSUE TITLE
Failing GRANT ON PROCEDURE to multiplie procedures

### ISSUE THREAD

**Issue by IgorIgnatevSky** [petoju/terraform-provider-mysql#170]
### Provider version
Terraform v1.9.5
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.27.0
+ provider registry.terraform.io/hashicorp/aws v4.39.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.15.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/hashicorp/vault v3.8.2
+ provider registry.terraform.io/petoju/mysql v3.0.63

### MySQL version and settings
RDS MySQL 8.0.35

### Terraform Configuration Files

```hcl
resource "mysql_grant" "privileges_kill" {
  user       = "test"
  host       = "%"
  database   = "PROCEDURE mysql"
  table      = "rds_kill"
  privileges = ["EXECUTE"]
}

resource "mysql_grant" "privileges_kill_query" {
  user       = "test"
  host       = "%"
  database   = "PROCEDURE mysql"
  table      = "rds_kill_query"
  privileges = ["EXECUTE"]
}
```

### Expected Behavior
The user should have 2 Grants for 2 procedures
```
GRANT EXECUTE ON PROCEDURE `mysql`.`rds_kill` TO `test`@`%`
GRANT EXECUTE ON PROCEDURE `mysql`.`rds_kill_query` TO `test`@`%`
```

### Actual Behavior
Only one grant (who is faster) is granted, and the second one is failing with an error. I tried different approaches and it doesn't matter what the second table name is, it will fail anyway.
successful grant:
```
GRANT EXECUTE ON PROCEDURE `mysql`.`rds_kill_query` TO `test`@`%`
```
second grant:
```
│ Error: user/role mysql.UserOrRole{Name:"test", Host:"%"} already has grant &{mysql PROCEDURE rds_kill_query [EXECUTE] false {test %} NONE} - 
│ 
│   with module.rds-2_users.mysql_grant.privileges_kill["test"],
│   on ../modules/database/mysql-users/main.tf line 57, in resource "mysql_grant" "privileges_kill":
│   57: resource "mysql_grant" "privileges_kill" {
```

### Steps to Reproduce
1. `terraform apply`

**Comment by petoju** [comment]
@IgorIgnatevSky  thanks - this should be fixed in 3.0.64

**Comment by IgorIgnatevSky** [comment]
I just wanted to let you know everything is ok. Thx for the quick fix

**Comment by IgorIgnatevSky** [comment]
Fixed
