### ISSUE TITLE
Error with 2 succcessive apply

### ISSUE THREAD

**Issue by ddup1** [petoju/terraform-provider-mysql#18]
Hi,

After i saw that mysql provider is no more maintained by Hashicorps, i search for an alternative and begin update to tf1.1 or 1.2

I found your mysql provider that is a fork from the original provider.

The first time i launch terraform apply, my db user are well created, but if i launch a terraform apply a second time, then i got an error : 

Error: Create user couldn't be parsed - it is CREATE USER `myuser`@`%` IDENTIFIED BY PASSWORD '*ABDEFGHIJKLMNOPR'

Any idea about this issue ? 

I use terraform 1.1.9 and mysql provider 3.0.17.

Regards.

**Comment by petoju** [comment]
@ddup1 this is fixed in 3.0.18.

**Comment by ddup1** [comment]
Hi,

thanks @petoju , will try this.

On my side i try to unify regexp for maria and mysql in one regexp but fail as it change the group count.

Thanks a lot.
