### ISSUE TITLE
mysql_global_variable with string value is not handled correctly

### ISSUE THREAD

**Issue by boltandrke** [petoju/terraform-provider-mysql#22]
### Terraform Version
0.14.7

### Affected Resource(s)
- mysql_global_variable

### Terraform Configuration Files
```hcl
resource "mysql_global_variable" "tidb_auto_analyze_end_time" {
    name  = "tidb_auto_analyze_end_time"
    value = "`7:00 +0300`"
}
```

### Expected Behavior
`terraform apply` should not change resource and just keep state

### Actual Behavior
is working but apply tries to change it every time ~ value = "07:00 +0300" -> "`7:00 +0300`"

### Steps to Reproduce
1. `terraform apply`

**Comment by petoju** [comment]
@boltandrke has this been fixed?

**Comment by boltandrke** [comment]
Yes, its resolved with latest PR
