### ISSUE TITLE
sensitive data broken link - mysql_user page

### ISSUE THREAD

**Issue by yoni-yad2** [petoju/terraform-provider-mysql#4]
This link is broken in the mysql_user [documentation](https://registry.terraform.io/providers/petoju/mysql/latest/docs/resources/user):
[Read more about sensitive data in state](https://registry.terraform.io/docs/state/sensitive-data)

Should be:
https://www.terraform.io/language/state/sensitive-data

**Comment by petoju** [comment]
Thanks, fixed and deployed.
