### ISSUE TITLE
Question: Create user WITH additional params.

### ISSUE THREAD

**Issue by ajax-mykhailo-oleksiuk** [petoju/terraform-provider-mysql#45]
Hi @petoju,

I've looked throught source code and don't see any chances to create a user with additional params like this:
```
CREATE USER 'francis'@'localhost' IDENTIFIED BY 'frank'
    ->     WITH MAX_QUERIES_PER_HOUR 20
    ->          MAX_UPDATES_PER_HOUR 10
    ->          MAX_CONNECTIONS_PER_HOUR 5
    ->          MAX_USER_CONNECTIONS 2;
```

1) Could you please confirm this?
2) Do you have any plans to add this or not?

**Comment by petoju** [comment]
1. Yes, there is no ability to do that.
2. I don't have any plans as I don't believe it really helps (one large query/update thru one connection can be much worse than 20 simple queries). That said, I will accept PRs adding this behavior, as long as the code quality is reasonable and as long as it won't break existing users.
