### ISSUE TITLE
Compatibility with MariaDB 10.10

### ISSUE THREAD

**Issue by mudkipme** [petoju/terraform-provider-mysql#52]
As of https://jira.mariadb.org/browse/MDEV-28554, MariaDB 10.10 removed `innodb_version` system variable.

That caused Terraform failed to apply `mysql_database` and `mysql_user` with the error output below:
```
Error: failed to connect to MySQL: failed running after connect command: Failed getting server version: Error 1193: Unknown system variable 'innodb_version'
```

**Comment by petoju** [comment]
@mudkipme would you consider writing a patch?

**Comment by petoju** [comment]
@mudkipme thanks for your patch, it was released.
